export { default as BlobBackgroundSVG } from './blob background.svg';

export { default as MeditatingPersonSVG } from './Meditation person.svg';
export { default as HomePageSvg } from './HomePageSVG.svg';
export { default as HappyFaceSvg } from './HappyFace.svg';
export { default as NeutralFaceSvg } from './NeutralFace.svg';
export { default as AngryFaceSvg } from './AngryFace.svg';
export { default as SadFaceSvg } from './SadFace.svg';
export { default as HomeIconSvg } from './Home.svg';
export { default as CommunityIconSvg } from './CommunityIconSvg.svg';
export { default as VoiceAnalyzeSvg } from './VoiceAnalyzeSvg.svg';
export { default as VoiceAnalyzeSvgSamll } from './VoiceAnalyzeSvgSmall.svg';
export { default as AssessmentSvg } from './AssessmentSvg.svg';
export { default as TasksSvg } from './RecommendedTasksSVG.svg';
export { default as HelpSvg } from './HelpSvg.svg';
export { default as UserIconSvg } from './UserIconSvg.svg';
export { default as HamburgerIconSvg } from './HamburgerIconSvg.svg';
export { default as NatureSvg } from './Nature.svg';
export { default as RecommendedTasksSVG } from './RecommendedTasksSVG.svg';
export { default as SleepingMoonSVG } from './SleepingMoon.svg';
export { default as SleepMonitorSVG } from './MonitorSleepSVG.svg';
export { default as ShareSVG } from './ShareSVG.svg';
export { default as DoctorSVG } from './Doctor.svg';
export { default as SleepSVG } from './SleepSVG.svg';
export { default as CalendarSVG } from './Calendar.svg';
export { default as DiarySVG } from './Diary.svg';
export { default as AddSVG } from './Add.svg';
export { default as DiarySmallSVG } from './DiarySmallSvg.svg';
export { default as DoctorPersonSVG } from './DoctorPerson.svg';
